language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
before_script:
  - cp administrador_encuestas/settings.py{.default,}
  - python manage.py migrate
script: coverage run manage.py test
after_success:
  - coveralls
