# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjunto',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensaje',
            },
        ),
        migrations.CreateModel(
            name='SendedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_sended', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Message')),
            ],
            options={
                'verbose_name': 'Mensaje enviado',
                'verbose_name_plural': 'Mensaje enviado',
            },
        ),
        migrations.CreateModel(
            name='SendedSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondida', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Encuesta enviada',
                'verbose_name_plural': 'Encuesta enviada',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'John Doe', max_length=32)),
                ('rut', models.CharField(default=b'123456789-1', max_length=12)),
                ('phone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=20)),
                ('conjunto', models.ManyToManyField(to='encuestas.Conjunto')),
            ],
            options={
                'verbose_name': 'Sujeto',
                'verbose_name_plural': 'Sujeto',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('url', models.URLField(default=b'www.google.cl')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuesta',
            },
        ),
        migrations.AddField(
            model_name='sendedsurvey',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Subject'),
        ),
        migrations.AddField(
            model_name='sendedsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Survey'),
        ),
        migrations.AddField(
            model_name='sendedmessage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Subject'),
        ),
    ]
