# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encuestas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjunto',
            },
        ),
        migrations.CreateModel(
            name='ConjuntosToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Conjunto')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=50, unique=True, verbose_name=b'Device ID')),
                ('reg_id', models.CharField(max_length=255, unique=True, verbose_name=b'Registration ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name')),
                ('is_active', models.BooleanField(default=False, verbose_name=b'Is active?')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensaje',
            },
        ),
        migrations.CreateModel(
            name='SendedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_sended', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Message')),
            ],
            options={
                'verbose_name': 'Mensaje enviado',
                'verbose_name_plural': 'Mensaje enviado',
            },
        ),
        migrations.CreateModel(
            name='SendedSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondida', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('messages', models.ManyToManyField(to='encuestas.SendedMessage')),
            ],
            options={
                'verbose_name': 'Encuesta enviada',
                'verbose_name_plural': 'Encuesta enviada',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'John Doe', max_length=32)),
                ('rut', models.CharField(default=b'123456789-1', max_length=12, validators=[encuestas.validators.verificar_rut])),
                ('phone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_connection', models.DateTimeField(null=True)),
                ('conjunto', models.ManyToManyField(to='encuestas.Conjunto')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.FCM_DEVICE_MODEL)),
            ],
            options={
                'verbose_name': 'Sujeto',
                'verbose_name_plural': 'Sujeto',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('url', models.URLField(default=b'www.google.cl')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('last_sended_date', models.DateTimeField(null=True)),
                ('sended', models.BooleanField(default=False)),
                ('end_survey_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuesta',
            },
        ),
        migrations.AddField(
            model_name='sendedsurvey',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Subject'),
        ),
        migrations.AddField(
            model_name='sendedsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Survey'),
        ),
        migrations.AddField(
            model_name='sendedmessage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Subject'),
        ),
    ]
