# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-28 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FCM_DEVICE_MODEL),
        ),
    ]
