# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_subject_last_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjutosToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Conjunto')),
            ],
        ),
    ]
