# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import encuestas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_auto_20170111_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedsurvey',
            name='messages',
            field=models.ManyToManyField(to='encuestas.SendedMessage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='rut',
            field=models.CharField(default=b'123456789-1', max_length=12, validators=[encuestas.validators.verificar_rut]),
        ),
    ]
